<?xml version="1.0" encoding="utf-8"?><Database Name="DemoDB" Class="LinqToSQlDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GRL-LT-136\FIRSTDEMOPROJECT;Initial Catalog=DemoDB;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="WpfApp1.Properties.Settings" SettingsPropertyName="DemoDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.University" Member="Universities">
    <Type Name="University">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="University_Student" Member="Students" ThisKey="Id" OtherKey="Universityid" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Universityid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Student_StudentLecture" Member="StudentLectures" ThisKey="Id" OtherKey="Studentid" Type="StudentLecture" />
      <Association Name="University_Student" Member="University" ThisKey="Universityid" OtherKey="Id" Type="University" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Lecture" Member="Lectures">
    <Type Name="Lecture">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Lecture_StudentLecture" Member="StudentLectures" ThisKey="Id" OtherKey="Lectureid" Type="StudentLecture" />
    </Type>
  </Table>
  <Table Name="dbo.StudentLecture" Member="StudentLectures">
    <Type Name="StudentLecture">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Studentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lectureid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lecture_StudentLecture" Member="Lecture" ThisKey="Lectureid" OtherKey="Id" Type="Lecture" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Student_StudentLecture" Member="Student" ThisKey="Studentid" OtherKey="Id" Type="Student" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>